### ISSUE TITLE
keyword list search

### ISSUE THREAD

**Issue by mgaulton** [sergiogiogio/torrentsearch#2]
hey there, 

I have a list of words "this word" "thisword" "this other word" each on a separate line and I want to have something load a keyword, search all results, download them and tag the link so its not downloaded again. your app comes closest to what I need. I was wondering if there's a way to have it autodownload all results, without waiting for selection?

**Comment by sergiogiogio** [comment]
Hello - currently the app is purely interactive so there is no way to auto download. The initial requirement was to be able to manually select the single "best" torrent (hence the filter and sort features). For automated download (and keeping track of history) - I would advise investigating  https://github.com/Flexget/Flexget . The discover plugin is able to search from popular torrents sites and pass down the result to download plugins.
